version: "3.8"

services:
  wildfly:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=password
      - DB_NAME=communications
      - DATASOURCE_NAME=PostgresDS
      - DATASOURCE_JNDI=java:/PostgresDS
    depends_on:
      - db

  db:
    image: postgres:15.3
    environment:
      POSTGRES_DB: communications
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./resources/db:/docker-entrypoint-initdb.d/
volumes:
  pg_data: